# Configuración básica
spring.application.name=api-gateway
server.port=8080

# Configuración Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Discovery Locator (genera rutas automáticamente)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Timeouts
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10000

# Default Filters
spring.cloud.gateway.default-filters[0]=TokenRelay
spring.cloud.gateway.default-filters[1]=PreserveHostHeader

# Configuraciones JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generation=${USER_GENERATOR}

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG