server:
  port: 8087

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/axelvega483/Microservicios-farmacia.git
          searchPaths: config-data
          username: ${GIT-USER}
          password: ${GIT-PASSWORD}
